# Copyright (c) 2021, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if .Values.wso2.deployment.am.websub.route.enabled }}

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "am-pattern-3.resource.prefix" . }}-am-websub-route
  namespace : {{ .Release.Namespace }}
spec:
  host: {{ .Values.wso2.deployment.am.websub.route.hostname }}
  to:
    kind: Service
    name: {{ template "am-pattern-3.resource.prefix" . }}-am-gateway-service
    weight: 100
  port:
    targetPort: 8021
  tls:
    termination: edge
  wildcardPolicy: None
{{- end -}}
